"""empty message
Revision ID: fae59c8efbfb
Revises: dbf01303e0ab
Create Date: 2021-08-19 17:25:36.065247
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fae59c8efbfb'
down_revision = 'dbf01303e0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('name', sa.String(), nullable=False))
    op.add_column('songs', sa.Column('artist', sa.String(), nullable=False))
    op.alter_column('songs', 'danceability',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('songs', 'key',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('songs', 'loudness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('songs', 'mode',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('songs', 'speechiness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('songs', 'acousticness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('songs', 'instrumentalness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('songs', 'liveness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('songs', 'valence',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('songs', 'tempo',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('songs', 'duration_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('songs', 'time_signature',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'time_signature',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('songs', 'duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('songs', 'tempo',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('songs', 'valence',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('songs', 'liveness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('songs', 'instrumentalness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('songs', 'acousticness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('songs', 'speechiness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('songs', 'mode',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('songs', 'loudness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('songs', 'key',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('songs', 'danceability',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('songs', 'artist')
    op.drop_column('songs', 'name')
    # ### end Alembic commands ###
